<?php
// diary/export.php
require_once '../config/config.php';
require_once '../config/db.php';
require_once '../includes/functions.php';

if (!isLoggedIn()) {
    redirect('login.php');
}

$user_id = $_SESSION['user_id'];
$entries = [];
$mode = isset($_GET['mode']) ? sanitize($_GET['mode']) : ''; // 'print' or 'view'
$year = isset($_GET['year']) ? (int)$_GET['year'] : date('Y');
$month = isset($_GET['month']) ? (int)$_GET['month'] : 0;

if ($mode == 'print') {
    // Fetch entries for export
    $sql = "SELECT d.*, c.name as chapter_name, col.name as collection_name 
            FROM diary_entries d
            LEFT JOIN chapters c ON d.chapter_id = c.id
            LEFT JOIN collections col ON d.collection_id = col.id
            WHERE d.user_id = ? AND YEAR(d.date_gregorian) = ?";
    
    if ($month > 0) {
        $sql .= " AND MONTH(d.date_gregorian) = $month";
    }
    
    $sql .= " ORDER BY d.date_gregorian ASC";
    
    $stmt = $conn->prepare($sql);
    $stmt->bind_param("ii", $user_id, $year);
    $stmt->execute();
    $entries = $stmt->get_result();
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MyDiary Archive - <?php echo $year . ($month ? "-$month" : ""); ?></title>
    <style>
        body { font-family: 'Inter', 'Segoe UI', serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 40px; }
        .entry { margin-bottom: 50px; page-break-inside: avoid; }
        .entry-title { font-size: 1.8rem; margin-bottom: 5px; color: #000; }
        .entry-meta { font-style: italic; color: #666; font-size: 0.9rem; margin-bottom: 15px; border-bottom: 1px solid #eee; padding-bottom: 5px; }
        .entry-content { font-size: 1.1rem; text-align: justify; }
        .badge { display: inline-block; padding: 2px 8px; font-size: 0.8rem; background: #eee; border-radius: 4px; margin-right: 5px; }
        footer { margin-top: 50px; text-align: center; font-size: 0.8rem; color: #999; }
        @media print {
            .no-print { display: none; }
            body { margin: 0; }
        }
    </style>
</head>
<body onload="window.print()">
    <div class="no-print" style="background: #f8f9fa; padding: 10px; margin-bottom: 20px; border-radius: 5px;">
        <button onclick="window.close()" style="padding: 5px 15px; cursor: pointer;">Close Preview</button>
        <span style="margin-left: 20px;">Use <strong>Ctrl + P</strong> to save as PDF if the dialog doesn't appear.</span>
    </div>

    <div class="header">
        <h1>Life Archive</h1>
        <p>A collection of memories by <?php echo htmlspecialchars($_SESSION['full_name']); ?></p>
        <h2><?php echo $month ? date('F Y', mktime(0,0,0,$month, 1, $year)) : "Year $year"; ?></h2>
    </div>

    <?php if ($entries->num_rows > 0): ?>
        <?php while($row = $entries->fetch_assoc()): ?>
            <div class="entry">
                <div class="entry-title"><?php echo htmlspecialchars($row['title']); ?></div>
                <div class="entry-meta">
                    <?php echo date('l, d F Y', strtotime($row['date_gregorian'])); ?>
                    <?php if ($row['date_hijri']): ?> | <?php echo htmlspecialchars($row['date_hijri']); ?><?php endif; ?>
                    <br>
                    <?php if ($row['mood']): ?><span class="badge">Mood: <?php echo htmlspecialchars($row['mood']); ?></span><?php endif; ?>
                    <?php if ($row['chapter_name']): ?><span class="badge">Chapter: <?php echo htmlspecialchars($row['chapter_name']); ?></span><?php endif; ?>
                    <?php if ($row['collection_name']): ?><span class="badge">Collection: <?php echo htmlspecialchars($row['collection_name']); ?></span><?php endif; ?>
                </div>
                <div class="entry-content">
                    <?php echo $row['content']; ?>
                </div>
            </div>
        <?php endwhile; ?>
    <?php else: ?>
        <p style="text-align: center; color: #666; margin-top: 100px;">No entries found for this period.</p>
    <?php endif; ?>

    <footer>
        Generated by <?php echo APP_NAME; ?> on <?php echo date('d M Y H:i'); ?>
    </footer>
</body>
</html>
<?php
    exit;
}

// Default View: UI to selection period
require_once '../includes/header.php';
?>

<div class="row justify-content-center">
    <div class="col-md-8">
        <div class="glass-card fade-in text-center">
            <h2 class="mb-4"><i class="fa-solid fa-file-pdf text-danger"></i> Life Archive & Export</h2>
            <p class="text-muted">Generate a clean, printable archive of your memories for offline keeping.</p>
            
            <form action="" method="GET" target="_blank" class="mt-5">
                <input type="hidden" name="mode" value="print">
                
                <div class="row g-3 justify-content-center">
                    <div class="col-md-5">
                        <label class="form-label">Select Year</label>
                        <select name="year" class="form-select">
                            <?php 
                            for($y = date('Y'); $y >= 2020; $y--) {
                                echo "<option value='$y'>$y</option>";
                            }
                            ?>
                        </select>
                    </div>
                    <div class="col-md-5">
                        <label class="form-label">Select Month (Optional)</label>
                        <select name="month" class="form-select">
                            <option value="0">Entire Year</option>
                            <?php 
                            for($m = 1; $m <= 12; $m++) {
                                $month_name = date('F', mktime(0,0,0,$m, 1));
                                echo "<option value='$m'>$month_name</option>";
                            }
                            ?>
                        </select>
                    </div>
                </div>

                <div class="mt-5 d-grid gap-2 col-md-6 mx-auto">
                    <button type="submit" class="btn btn-primary btn-lg shadow">
                        <i class="fa-solid fa-file-export me-2"></i> Generate Archive Archive
                    </button>
                    <div class="form-text text-start">
                        <i class="fa-solid fa-circle-info"></i> Your browser's print dialog will open. Select "Save as PDF" as the destination.
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

<?php require_once '../includes/footer.php'; ?>
