<?php
// includes/ImageGenerator.php

class ImageGenerator {
    private $conn;

    public function __construct($db) {
        $this->conn = $db;
    }

    /**
     * Generates a shareable card image
     * 
     * @param array $entry Entry data
     * @param string $theme 'modern', 'vintage', 'dark'
     * @return string Path to generated image
     */
    public function generateCard($entry, $theme = 'modern') {
        // Dimensions
        $width = 800;
        $height = 1000;
        $img = imagecreatetruecolor($width, $height);

        // Colors based on theme
        if ($theme == 'dark') {
            $bgColor = imagecolorallocate($img, 33, 37, 41);
            $textColor = imagecolorallocate($img, 248, 249, 250);
            $accentColor = imagecolorallocate($img, 13, 110, 253);
        } elseif ($theme == 'vintage') {
            $bgColor = imagecolorallocate($img, 244, 235, 219);
            $textColor = imagecolorallocate($img, 92, 64, 51);
            $accentColor = imagecolorallocate($img, 160, 82, 45);
        } else { // modern
            $bgColor = imagecolorallocate($img, 255, 255, 255);
            $textColor = imagecolorallocate($img, 33, 37, 41);
            $accentColor = imagecolorallocate($img, 13, 110, 253);
        }

        imagefill($img, 0, 0, $bgColor);

        // Simple Draw (No TTF support assumed for simplicity/portability, but using builtin if needed)
        // Note: Builtin fonts are limited. For "WOW" impact, TTF is better, but requires font files.
        // I will use imagestring for basic layout, but ideally I'd use imagettftext if fonts were provided.
        // However, I can draw rectangles for a "Designed" look.
        
        // Accents
        imagefilledrectangle($img, 0, 0, $width, 50, $accentColor);
        imagefilledrectangle($img, 0, $height - 50, $width, $height, $accentColor);

        // Title
        imagestring($img, 5, 50, 100, "MEMORIES FROM MY DIARY", $textColor);
        imagestring($img, 5, 50, 130, strtoupper($entry['title']), $accentColor);
        
        // Date
        $dateStr = date('d F Y', strtotime($entry['date_gregorian']));
        imagestring($img, 3, 50, 160, $dateStr, $textColor);

        // Content (Wrapped)
        $cleanContent = strip_tags(htmlspecialchars_decode($entry['content']));
        $lines = explode("\n", wordwrap($cleanContent, 60, "\n"));
        $y = 220;
        foreach ($lines as $line) {
            if ($y > 850) break; // Don't run off bottom
            imagestring($img, 4, 80, $y, trim($line), $textColor);
            $y += 25;
        }

        // Signature/Branding
        imagestring($img, 3, $width - 200, $height - 80, "Generated by MyDiary", $bgColor);

        // Save to temp
        $filename = 'card_' . $entry['id'] . '_' . time() . '.png';
        $path = '../assets/uploads/cards/' . $filename;
        
        // Create dir if not exists
        if (!is_dir('../assets/uploads/cards/')) {
            mkdir('../assets/uploads/cards/', 0777, true);
        }

        imagepng($img, $path);
        imagedestroy($img);

        return 'assets/uploads/cards/' . $filename;
    }
}
